---
title: "EDLD 610 Winter 2020 Project Proposal"
author: "Jim Wright"
date: "1/28/2020"
output: html_document
toc: true
toc_float: true 
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      dev.args = list(bg="transparent"))

library(tidyverse)
library(rio)
library(here)

all_ages <- import(here("data", "all-ages.csv"),
               setclass = "tbl_df")

grad_students <- import(here("data", "grad-students.csv"),
               setclass = "tbl_df")

majors_lists <- import(here("data", "majors-list.csv"),
               setclass = "tbl_df")

recent_grads <- import(here("data", "recent-grads.csv"),
               setclass = "tbl_df")

women_stem <- import(here("data", "women-stem.csv"),
               setclass = "tbl_df")

```

# Data Description: 
The data to be used for this project consists of five data sets from the FiveThirtyEight GitHub page. (https://github.com/fivethirtyeight/data/tree/master/college-majors). All data is from American Community Survey 2010-2012 Public Use Microdata Series.


# Information from the FiveThirtyEight GitHub page on the data
majors-list.csv

List of majors with their FOD1P codes and major categories.
Major categories are from Carnevale et al, "What's It Worth?: The Economic Value of College Majors." Georgetown University Center on Education and the Workforce, 2011. http://cew.georgetown.edu/whatsitworth
Three main data files:

all-ages.csv
recent-grads.csv (ages <28)
grad-students.csv (ages 25+)
All contain basic earnings and labor force information. recent-grads.csv contains a more detailed breakdown, including by sex and by the type of job they got. grad-students.csv contains details on graduate school attendees.

Additionally, women-stem.csv contains data for scatter plot in associated DataLab post on women in science/technology jobs. It is a subset of recent-grads.csv. (Small easter egg: Check out my related Shiny app: https://bencasselman.shinyapps.io/new-test/)


