---
title: "State of the State Map Fun"
author: "Jim Wright"
date: "2/9/2020"
output: html_document
toc: true
toc_float: true
theme: united 
highlight: zenburn 
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      dev.args = list(bg="transparent"))

library(tidyverse)
library(rio)
library(here)
library(colorblindr)
library(gghighlight)
library(forcats)
library(ggrepel)


index <- import(here("data", "index.csv"),
               setclass = "tbl_df") %>% 
               janitor::clean_names() 

words <- import(here("data", "words.csv"),
               setclass = "tbl_df") %>% 
               janitor::clean_names() 

head(index)

head(words)


```

```{r map, include=TRUE}

library(ggmap)
library(maps)
library(mapdata)

states <- map_data("state") %>% 
  rename(state = region) %>% 
  mutate(state = stringr::str_to_title(state))


head(states)


ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = state, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)


index_map <- full_join(index, states)

head(index_map)

ggplot(index_map) +
  geom_polygon(aes(x = long,
                   y = lat, 
                   fill = party, 
                   group = group), color = "white") +
  scale_fill_manual(values = c("blue", "red", "black")) +
  coord_fixed(1.3) +
  labs(x = "",
       y = "",
       fill = "Political Party Affiliation") +
   theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key.size = unit(1.0, 'cm'),
        legend.key.height = unit(0.5,"cm"),
        legend.title=element_text(size=10))


ggplot(index_map) +
  geom_polygon(aes(x = long,
                   y = lat, 
                   fill = party, 
                   group = group), color = "white") +
  scale_fill_manual(values = c("blue", "red", "black")) +
  geom_text(aes(x = long, 
                y = lat, 
                label = governor)) +
  coord_fixed(1.3) +
  labs(x = "",
       y = "",
       fill = "Political Party Affiliation") +
   theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.key.size = unit(1.0, 'cm'),
        legend.key.height = unit(0.5,"cm"),
        legend.title=element_text(size=10))

```
